### ISSUE TITLE
Feature Request: RSS support

### ISSUE THREAD

**Issue by ykyu** [satopian/poti-kaini-EN#4]
Would it be possible to include an RSS/Atom feed in the future so users can subscribe to the BBS and be notified of new posts?

**Comment by satopian** [comment]
I created it at https://feedly.com/ and tested it, but found a problem.
Unlike blogs, it is a bulletin board that anyone can write.
There may be inappropriate posts that need to be deleted immediately.
However, if you delete the article, https: //feedly.com/ will still display the article.
This increases the risk.
Unfortunately, I can't add rss functionality.
I look forward to your continued patronage of POTI-Board.

**Comment by ykyu** [comment]
While many feed readers, including Feedly, do not delete posts when they are deleted from RSS, they _do_ usually support updated posts. So when deleting an inappropriate post from the BBS, the RSS file can be [updated](https://www.seroundtable.com/archives/017315.html) to say something like "content has been removed" and the post in Feedly and other readers should then be updated. This isn't a perfect solution, but I feel it's an acceptable workaround given the benefits of RSS overall. Having a way to be alerted with a new post is made keeps users more interested in the BBS and community.

The risk remains that an admin isn't available to immediately delete inappropriate content in the first place. This will always be a risk with open, anonymous BBS. The lack of pre-moderation was what made BBS attractive 10-15 years ago, but while I'm glad to see that there are still people using BBS, I think it's worth considering ways to make it more safe and less prone to inappropriate uses.

Maybe it would be a good idea to implement a universal user password, similar to the admin password, that users need to be able to post at all. Another idea is implementing a post queue, where an admin must manually approve new posts before they are displayed.

Thanks for your consideration and time in maintaining POTI-Board!

**Comment by satopian** [comment]
I'm sorry I didn't meet your expectations.
An email notification is a way for admins to quickly detect unintended posts and remove them.
[poti-kaini-EN/noticemail at main · satopian/poti-kaini-EN](https://github.com/satopian/poti-kaini-EN/tree/main/noticemail)
I also bookmark the comment list in search.php to see it.
It's sorted by post, not thread, so you'll know if there's an inappropriate post.
search.php is PHP for searching that is displayed when you click the name of the poster.

Please understand that there are other methods as well.

Regarding the reflection of the deletion of Feedly's article, it is a Japanese article, but I found something like this.
[Feedlyは記事を削除してもキャッシュは消えない。仕様です。 | りんか ネット](https://rin-ka.net/feedly-cache-delete/#:~:text=%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82-,%E3%81%BE%E3%81%A8%E3%82%81,%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E5%87%BA%E6%9D%A5%E3%81%BE%E3%81%99%E3%80%82)
This is the same as what I actually felt when I was working.
It is possible for many people to understand this and still use it, and to take responsibility for it, but I don't think many people understand the negative consequences of rss.
That's why I stopped supporting rss.
I maked a program to output with atom, but it didn't see the light of day to avoid risk.
Please understand.
Also, since the direction of development of this bulletin board is not account-oriented and we did not have such a development policy, we are not thinking about the method of acquiring an account for each user at this time.
This is because there are cultural differences between drawing forums outside Japan and drawing boards in Japan.
This is just an idea at this point, so I may fix it.
Thank you.
