### ISSUE TITLE
Change default paint program?

### ISSUE THREAD

**Issue by catharsis71** [satopian/poti-kaini-EN#5]
New visitors seem to always have Shi-Painter set as the default paint program option:

![image](https://user-images.githubusercontent.com/70603733/180513513-b2024af4-6f43-4237-8566-3eb7efb81318.png)

this is probably the worst choice for a default because it loads very slowly & sometimes doesn't load at all

I don't want to disable Shi-Painter completely in case someone likes it but I want to change the default to something else preferably via my config.php

How can I do this?

**Comment by satopian** [comment]
@catharsis71 
shi-Painter is not the default setting.
If shi-Painter is already selected, it's a cookie.
The cookie remembers the last tool you used.
And on the smartphone, it is set with JavaScript so that shi-Painter cannot be selected.

**Comment by catharsis71** [comment]
I apologize, I tested again in a private window and it's actually PaintBBS Neo that's the default.

But if I wanted to set ChickenPaint or Klercks as the default (without disabling any of them) would that be possible to do?

**Comment by satopian** [comment]
@catharsis71 
![select_app](https://user-images.githubusercontent.com/44894014/180603539-9826bed3-229f-45c4-bc42-d0946676091c.gif)
edit `poti-kaini-EN\potiboard5\templates\mono_en\mono_main.blade.php`.
```
		@if($select_app)
			Tool:
			<select name="shi">
				@if ($use_klecks)<option value="klecks">Klecks</option>@endif
				@if($use_chickenpaint)<option value="chicken">ChickenPaint</option>@endif
			<option value="neo">PaintBBS NEO</option>
			@if($use_shi_painter)<option value="1" class="for_pc">Shi-Painter</option>@endif
		</select>
		@else 
		{{-- <!-- 選択メニューを出さない時に起動するアプリ --> --}}
		<input type="hidden" name="shi" value="neo">
		@endif

```
In this example, klecks, chickenpaint, PaintBBS, shi-Painter are listed in that order.
If I change this part to use an array, the sort will be in the order of the array, but I can't ask the end user to set a multidimensional associative array, so it's on hold.
However, no matter how they are lined up, if the last app you used is klecks, klecks will be selected.
If the last app you used is Chicken Paint, then Chicken Paint will be will be selected.
That's because it's remembered by cookies.
